/**
 * ⚠️ SAMPLE / DEMO DATA ⚠️
 * Everything in this file (properties, blog posts, gallery items) is
 * placeholder content used to preview the site's layout. None of it is
 * real. Before the site goes live for a real client, either:
 *   1) Replace the entries below with your actual listings and posts, or
 *   2) Leave this file alone and use the /admin panel (Login page) to
 *      add, edit, and delete real properties/blog posts once the site
 *      is deployed — the admin panel writes to the same database.
 */
import bcrypt from "bcryptjs";
import type { Collection } from "mongodb";
import { getDb } from "./mongodb.ts";
import type { BlogPostDoc, CommunityDoc, DeveloperDoc, GalleryItemDoc, MarketInsightDoc, ProjectDoc, PropertyDoc, UserDoc } from "./models.ts";

const now = new Date();

const properties: Omit<PropertyDoc, "_id">[] = [
  {
    slug: "canal-studio-business-bay",
    title: "Canal Studio",
    location: "Business Bay",
    community: "Business Bay",
    type: "Apartment",
    listingType: "rent",
    status: "For rent",
    price: 62000,
    currency: "AED",
    bedrooms: 0,
    bathrooms: 1,
    size: 480,
    description: "A compact studio on the canal walk, let furnished, with a balcony facing the water and the towers beyond.",
    images: ["/images/business-bay-night.jpg", "/images/downtown-safa-park.jpg"],
    amenities: ["Furnished", "Pool", "Gym", "Canal walk access"],
    featured: false,
    published: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "circle-gardens-jvc",
    title: "Circle Gardens",
    location: "Jumeirah Village Circle",
    community: "Jumeirah Village Circle",
    type: "Apartment",
    listingType: "rent",
    status: "For rent",
    price: 105000,
    currency: "AED",
    bedrooms: 2,
    bathrooms: 2,
    size: 1150,
    description: "A two-bedroom apartment in a low-rise block, with a wide balcony over the district's landscaped circle.",
    images: ["/images/difc-green-towers.jpg", "/images/community-garden-villas.jpg"],
    amenities: ["Covered parking", "Shared pool", "Gym", "Children's play area"],
    featured: false,
    published: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "park-row-dubai-hills",
    title: "Park Row",
    location: "Dubai Hills Estate",
    community: "Dubai Hills Estate",
    type: "Townhouse",
    listingType: "rent",
    status: "For rent",
    price: 255000,
    currency: "AED",
    bedrooms: 3,
    bathrooms: 4,
    size: 2150,
    description: "A three-bedroom townhouse on a quiet park-facing row, with a private garden and a maid's room off the kitchen.",
    images: ["/images/community-garden-villas.jpg", "/images/marina-resort-greens.jpg"],
    amenities: ["Private garden", "Maid's room", "Community park", "Two parking bays"],
    featured: false,
    published: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "saheel-villa-arabian-ranches",
    title: "Saheel Villa",
    location: "Saheel, Arabian Ranches",
    community: "Arabian Ranches",
    type: "Villa",
    listingType: "rent",
    status: "For rent",
    price: 375000,
    currency: "AED",
    bedrooms: 4,
    bathrooms: 5,
    size: 3400,
    description: "A family villa on a landscaped street, with a private pool, a separate majlis, and the golf course a short drive away.",
    images: ["/images/dubai-creek-dusk.jpg", "/images/community-garden-villas.jpg"],
    amenities: ["Private pool", "Majlis", "Maid's room", "Landscaped garden"],
    featured: false,
    published: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "lake-level-office-jlt",
    title: "Lake Level Office",
    location: "Cluster R, Jumeirah Lake Towers",
    community: "Jumeirah Lake Towers",
    type: "Office",
    listingType: "rent",
    status: "For rent",
    price: 150000,
    currency: "AED",
    bedrooms: 0,
    bathrooms: 2,
    size: 1600,
    description: "A fitted office floor overlooking the lakes, partitioned for a small team, with metro access at the door.",
    images: ["/images/sheikh-zayed-road-towers.jpg", "/images/dubai-marina-promenade.jpg"],
    amenities: ["Fitted and partitioned", "Chilled water included", "Metro access", "Visitor parking"],
    featured: false,
    published: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "square-house-town-square",
    title: "Square House",
    location: "Town Square",
    community: "Town Square",
    type: "Townhouse",
    listingType: "sale",
    status: "For sale",
    price: 2350000,
    currency: "AED",
    bedrooms: 3,
    bathrooms: 4,
    size: 1950,
    description: "A three-bedroom townhouse a short walk from the central park, built for families who want space without leaving the city.",
    images: ["/images/jumeirah-coast-burj-al-arab.jpg", "/images/community-garden-villas.jpg"],
    amenities: ["Central park", "Community pool", "Cycle paths", "Private garden"],
    featured: false,
    published: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "canal-duplex-business-bay",
    title: "Canal Duplex",
    location: "Business Bay",
    community: "Business Bay",
    type: "Duplex",
    listingType: "sale",
    status: "For sale",
    price: 5800000,
    currency: "AED",
    bedrooms: 3,
    bathrooms: 4,
    size: 2400,
    description: "A two-storey residence high in the tower, with double-height glazing to the canal and a separate entertaining floor.",
    images: ["/images/burj-night-water.jpg", "/images/business-bay-night.jpg"],
    amenities: ["Double-height living", "Canal views", "Private lift lobby", "Two parking bays"],
    featured: true,
    published: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "cluster-office-jlt",
    title: "Cluster Office Floor",
    location: "Cluster X, Jumeirah Lake Towers",
    community: "Jumeirah Lake Towers",
    type: "Office",
    listingType: "sale",
    status: "For sale",
    price: 3200000,
    currency: "AED",
    bedrooms: 0,
    bathrooms: 2,
    size: 2100,
    description: "A freehold office floor with lake frontage on three sides, sold with its fit-out and dedicated parking.",
    images: ["/images/hero-dubai-skyline.jpg", "/images/sheikh-zayed-road-towers.jpg"],
    amenities: ["Freehold", "Fitted", "Lake frontage", "Dedicated parking"],
    featured: false,
    published: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "palm-jumeirah-azure",
    title: "Azure House",
    location: "Frond M, Palm Jumeirah",
    community: "Palm Jumeirah",
    type: "Villa",
    status: "For sale",
    price: 24500000,
    currency: "AED",
    bedrooms: 5,
    bathrooms: 7,
    size: 8420,
    description: "A private waterfront villa shaped around quiet mornings, generous entertaining, and direct access to the water.",
    images: ["/images/hero-dubai-villa.jpg", "/images/palm-jumeirah-aerial.jpg"],
    amenities: ["Private beach", "Infinity pool", "Staff suite", "Sea views"],
    featured: true,
    published: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "meridian-residence-dubai-marina",
    title: "The Meridian Residence",
    location: "Dubai Marina",
    community: "Dubai Marina",
    type: "Penthouse",
    status: "For sale",
    price: 8900000,
    currency: "AED",
    bedrooms: 3,
    bathrooms: 4,
    size: 2980,
    description: "A turnkey skyline residence with a wide marina outlook and a considered, light-filled interior.",
    images: ["/images/penthouse-marina.jpg", "/images/dubai-marina-promenade.jpg"],
    amenities: ["Sea view", "Concierge", "Residents lounge", "Private lift"],
    featured: true,
    published: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "courtyard-17-dubai-hills",
    title: "Courtyard 17",
    location: "Dubai Hills Estate",
    community: "Dubai Hills Estate",
    type: "Villa",
    status: "For sale",
    price: 11750000,
    currency: "AED",
    bedrooms: 4,
    bathrooms: 5,
    size: 4870,
    description: "A calm contemporary family home on a quiet street, with garden rooms that bring the outside in.",
    images: ["/images/marina-resort-greens.jpg", "/images/community-garden-villas.jpg"],
    amenities: ["Private garden", "Study", "Garage", "Community pool"],
    featured: false,
    published: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "address-sky-view-downtown",
    title: "The Address Sky View",
    location: "Downtown Dubai",
    community: "Downtown Dubai",
    type: "Apartment",
    status: "For sale",
    price: 4250000,
    currency: "AED",
    bedrooms: 2,
    bathrooms: 3,
    size: 1640,
    description: "A polished city apartment with Burj Khalifa views and the service of one of Downtown’s most recognisable addresses.",
    images: ["/images/creek-waterfront.jpg", "/images/hero-dubai-skyline.jpg"],
    amenities: ["Burj view", "Valet parking", "Pool", "Fitness studio"],
    featured: false,
    published: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "garden-residence-jumeirah",
    title: "Garden Residence",
    location: "Jumeirah 2",
    community: "Jumeirah",
    type: "Villa",
    listingType: "sale",
    status: "For sale",
    price: 13800000,
    currency: "AED",
    bedrooms: 4,
    bathrooms: 5,
    size: 5200,
    description: "A leafy Jumeirah residence with generous proportions, considered landscaping, and a private pool.",
    images: ["/images/madinat-jumeirah-canal.jpg", "/images/jumeirah-coast-burj-al-arab.jpg"],
    amenities: ["Private pool", "Garden", "Maid's room", "Covered parking"],
    highlights: ["Quiet residential street", "Minutes from the beach"],
    featured: false,
    published: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "creekside-loft",
    title: "Creekside Loft",
    location: "Dubai Creek Harbour",
    community: "Dubai Creek Harbour",
    type: "Apartment",
    listingType: "sale",
    status: "For sale",
    price: 2850000,
    currency: "AED",
    bedrooms: 2,
    bathrooms: 2,
    size: 1350,
    description: "A bright, high-floor apartment with a wide water outlook and an easy connection to the new Creek neighbourhood.",
    images: ["/images/interior-detail.jpg", "/images/downtown-safa-park.jpg"],
    amenities: ["Water view", "Pool", "Gym", "Concierge"],
    highlights: ["High floor", "Walkable waterfront"],
    featured: false,
    published: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "marina-sunline",
    title: "Marina Sunline",
    location: "Dubai Marina",
    community: "Dubai Marina",
    type: "Apartment",
    listingType: "rent",
    status: "For rent",
    price: 220000,
    currency: "AED",
    bedrooms: 1,
    bathrooms: 2,
    size: 980,
    description: "A fully furnished marina apartment with sunset-facing views, hotel-style amenities, and a polished finish.",
    images: ["/images/dubai-marina-dusk.jpg", "/images/dubai-marina-promenade.jpg"],
    amenities: ["Furnished", "Pool", "Gym", "Parking"],
    highlights: ["Available now", "Sunset view"],
    featured: false,
    published: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "desert-modern-al-barari",
    title: "Desert Modern",
    location: "Al Barari",
    community: "Al Barari",
    type: "Villa",
    listingType: "sale",
    status: "For sale",
    price: 17900000,
    currency: "AED",
    bedrooms: 5,
    bathrooms: 6,
    size: 6900,
    description: "A sculptural family home surrounded by greenery, with a private courtyard and a calm indoor-outdoor rhythm.",
    images: ["/images/hills-villa.jpg", "/images/community-garden-villas.jpg"],
    amenities: ["Courtyard", "Private pool", "Cinema", "Smart home"],
    highlights: ["Landscaped setting", "Architect-designed"],
    featured: false,
    published: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "city-light-downtown",
    title: "City Light Residence",
    location: "Downtown Dubai",
    community: "Downtown Dubai",
    type: "Apartment",
    listingType: "sale",
    status: "For sale",
    price: 3650000,
    currency: "AED",
    bedrooms: 2,
    bathrooms: 2,
    size: 1480,
    description: "A refined city base with clean lines, skyline views, and direct access to Downtown's cultural and retail life.",
    images: ["/images/downtown-night-aerial.jpg", "/images/hero-dubai-skyline.jpg"],
    amenities: ["Skyline view", "Pool", "Valet parking", "Residents lounge"],
    highlights: ["Turnkey condition", "Central address"],
    featured: false,
    published: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "canal-house-business-bay",
    title: "Canal House",
    location: "Business Bay",
    community: "Business Bay",
    type: "Apartment",
    listingType: "sale",
    status: "For sale",
    price: 3150000,
    currency: "AED",
    bedrooms: 2,
    bathrooms: 3,
    size: 1420,
    description: "A composed canal-side residence with generous daylight, clean architectural lines, and a connected central address.",
    images: ["/images/downtown-safa-park.jpg", "/images/business-bay-night.jpg"],
    amenities: ["Canal view", "Pool", "Gym", "Concierge"],
    highlights: ["Central location", "Move-in ready"],
    featured: false,
    published: true,
    createdAt: now,
    updatedAt: now,
  },
];

const projects: Omit<ProjectDoc, "_id">[] = [
  {
    slug: "bay-grove-dubai-islands",
    title: "Bay Grove Residences",
    developer: "Nakheel",
    category: "Apartments",
    location: "Dubai Islands",
    startingPrice: 2400000,
    handover: "Q2 2030",
    status: "Launching",
    newLaunch: true,
    description: "A beachfront collection of apartments on Dubai Islands, arranged around a shoreline park and a private stretch of sand.",
    image: "/images/palm-jumeirah-aerial.jpg",
    featured: false,
    published: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "binghatti-circle-jvc",
    title: "Binghatti Circle",
    developer: "Binghatti",
    category: "Apartments",
    location: "Jumeirah Village Circle",
    startingPrice: 950000,
    handover: "Q1 2027",
    status: "Under construction",
    description: "A studio-to-two-bedroom tower in the centre of the district, with a payment plan that runs to handover.",
    image: "/images/dubai-marina-promenade.jpg",
    featured: false,
    published: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "the-oasis-by-emaar",
    title: "The Oasis",
    developer: "Emaar",
    category: "Villas",
    location: "Dubailand",
    startingPrice: 5500000,
    handover: "Q4 2028",
    description: "A low-density collection of villas and gardens designed around water, landscape, and long-term liveability.",
    image: "/images/palm-jumeirah-avenue.jpg",
    featured: true,
    published: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "bay-by-cavalli",
    title: "Bay by Cavalli",
    developer: "DAMAC",
    category: "Waterfront",
    location: "Dubai Maritime City",
    startingPrice: 3200000,
    handover: "Q2 2028",
    description: "A waterfront address for buyers looking for a distinctive design language, resort amenities, and a central coastal position.",
    image: "/images/maritime-city-towers.jpg",
    featured: true,
    published: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "the-valley-by-emaar",
    title: "The Valley",
    developer: "Emaar",
    location: "Jebel Ali",
    category: "Villas",
    status: "Launching",
    startingPrice: 2900000,
    handover: "Q1 2029",
    completionDate: "Q1 2029",
    description: "A new collection of family villas set around open landscapes, trails, and everyday community life.",
    image: "/images/jebel-ali-beach-towers.jpg",
    gallery: ["/images/hills-villa.jpg", "/images/creek-waterfront.jpg"],
    amenities: ["Community pool", "Sports fields", "Trails", "Town centre"],
    highlights: ["Family-oriented community", "Flexible payment plan"],
    featured: false,
    published: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "sobha-one",
    title: "Sobha One",
    developer: "Sobha Realty",
    location: "Ras Al Khor",
    category: "Apartments",
    status: "Under construction",
    startingPrice: 2100000,
    handover: "Q4 2028",
    description: "A golf-side vertical neighbourhood with generous views, thoughtful amenities, and a strong central position.",
    image: "/images/burj-khalifa-aerial.jpg",
    featured: false,
    published: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "avenue-al-jaddaf",
    title: "Avenue",
    developer: "Azizi",
    location: "Al Jaddaf",
    category: "Waterfront",
    status: "Launching",
    startingPrice: 1250000,
    handover: "Q3 2027",
    description: "A compact waterfront address for buyers seeking access, amenity, and a considered entry into the Dubai market.",
    image: "/images/marina-palm-view.jpg",
    featured: false,
    published: true,
    createdAt: now,
    updatedAt: now,
  },
];

const posts: Omit<BlogPostDoc, "_id">[] = [
  {
    slug: "where-to-live-in-dubai",
    title: "Where to live in Dubai when the city needs to feel like home",
    excerpt: "A local read on choosing between the energy of Downtown, the water of the Marina, and the space of the suburbs.",
    content: "Dubai rewards a slower first question: how do you want an ordinary Tuesday to feel? From walkable city life to private garden streets, the right community is the one that supports the life you are building.",
    category: "Area guide",
    image: "/images/creek-waterfront.jpg",
    author: "KNC Horizon",
    published: true,
    publishedAt: now,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "buying-off-plan-in-dubai",
    title: "A clear-eyed guide to buying off-plan in Dubai",
    excerpt: "The questions worth asking about a developer, a handover, a payment plan, and the value of a future address.",
    content: "Off-plan property can offer access to a new generation of communities, but the strongest decisions come from context. Understand the developer, the delivery timeline, the surrounding infrastructure, and how the payment plan fits your horizon.",
    category: "Investment",
    image: "/images/interior-detail.jpg",
    author: "KNC Horizon",
    published: true,
    publishedAt: now,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "the-dubai-rental-reset",
    title: "The Dubai rental reset: what tenants should look for now",
    excerpt: "A practical checklist for comparing a home beyond the headline rent.",
    content: "The strongest rental decisions come from looking at the whole year, not only the first month. Consider the building, the commute, the renewal terms, the maintenance response, and the daily ease of the address.",
    category: "Renting",
    image: "/images/penthouse-marina.jpg",
    author: "KNC Horizon",
    published: true,
    publishedAt: now,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "designing-a-better-home-search",
    title: "Designing a better home search",
    excerpt: "The right shortlist is not the longest one. It is the one that makes the decision clearer.",
    content: "A good search begins with a few strong filters and the confidence to remove what does not fit. When the brief reflects how you actually live, the right homes become easier to recognise.",
    category: "Perspective",
    image: "/images/hero-dubai-villa.jpg",
    author: "KNC Horizon",
    published: true,
    publishedAt: now,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "a-first-time-buyers-map",
    title: "A first-time buyer's map of Dubai",
    excerpt: "The questions that help a first purchase feel like a confident beginning.",
    content: "Start with the life you want to support, then work backwards through location, building quality, budget, and timeline. A property is a financial decision, but it is also a daily one.",
    category: "Buying",
    image: "/images/hills-villa.jpg",
    author: "KNC Horizon",
    published: true,
    publishedAt: now,
    createdAt: now,
    updatedAt: now,
  },
];

const gallery: Omit<GalleryItemDoc, "_id">[] = [
  { title: "Downtown after dark", category: "Skyline", image: "/images/downtown-night-aerial.jpg", alt: "Downtown Dubai and Sheikh Zayed Road lit up at night, seen from above", published: true, createdAt: now },
  { title: "The tower from the air", category: "Architecture", image: "/images/burj-khalifa-aerial.jpg", alt: "Burj Khalifa above the Downtown Dubai skyline in daylight", published: true, createdAt: now },
  { title: "Business Bay at blue hour", category: "Skyline", image: "/images/business-bay-night.jpg", alt: "Business Bay towers reflected in the Dubai Water Canal at night", published: true, createdAt: now },
  { title: "The marina at dusk", category: "Communities", image: "/images/dubai-marina-dusk.jpg", alt: "Dubai Marina towers and the marina walk at dusk", published: true, createdAt: now },
  { title: "Along the marina walk", category: "Communities", image: "/images/dubai-marina-promenade.jpg", alt: "The Dubai Marina promenade curving past the towers in daylight", published: true, createdAt: now },
  { title: "The Palm from above", category: "Waterfront", image: "/images/palm-jumeirah-aerial.jpg", alt: "Palm Jumeirah and its fronds seen from the air", published: true, createdAt: now },
  { title: "The road onto the Palm", category: "Communities", image: "/images/palm-jumeirah-avenue.jpg", alt: "A palm-lined avenue on Palm Jumeirah under a clear sky", published: true, createdAt: now },
  { title: "Madinat waterways", category: "Waterfront", image: "/images/madinat-jumeirah-canal.jpg", alt: "A canal at Madinat Jumeirah with the Burj Al Arab beyond the palms", published: true, createdAt: now },
  { title: "The Jumeirah coast", category: "Waterfront", image: "/images/jumeirah-coast-burj-al-arab.jpg", alt: "The Jumeirah coastline with the Burj Al Arab and the city behind it", published: true, createdAt: now },
  { title: "Green between the towers", category: "Communities", image: "/images/marina-resort-greens.jpg", alt: "Landscaped gardens and pools below the towers on the Dubai coast", published: true, createdAt: now },
  { title: "Room to breathe", category: "Villas", image: "/images/community-garden-villas.jpg", alt: "A low-rise villa community set among gardens and pools", published: true, createdAt: now },
  { title: "The city from Safa Park", category: "Skyline", image: "/images/downtown-safa-park.jpg", alt: "Downtown Dubai and Business Bay seen across the water from Safa Park", published: true, createdAt: now },
  { title: "Sheikh Zayed Road", category: "Architecture", image: "/images/sheikh-zayed-road-towers.jpg", alt: "Towers lining Sheikh Zayed Road in daylight", published: true, createdAt: now },
  { title: "Towers and gardens", category: "Architecture", image: "/images/difc-green-towers.jpg", alt: "High-rise towers above landscaped ground near the financial district", published: true, createdAt: now },
  { title: "Evening on the creek", category: "Waterfront", image: "/images/dubai-creek-dusk.jpg", alt: "Dubai Creek at dusk with the old quarter along the waterline", published: true, createdAt: now },
  { title: "Coastal high-rise", category: "Off-Plan", image: "/images/maritime-city-towers.jpg", alt: "Residential towers on the Dubai coast above a landscaped resort", published: true, createdAt: now },
  { title: "Where the city meets the sand", category: "Off-Plan", image: "/images/jebel-ali-beach-towers.jpg", alt: "The Jebel Ali shoreline with residential towers along the beach", published: true, createdAt: now },
  { title: "Night over the water", category: "Skyline", image: "/images/burj-night-water.jpg", alt: "The Dubai skyline at night seen across open water", published: true, createdAt: now },
  { title: "The marina and the Palm", category: "Waterfront", image: "/images/marina-palm-view.jpg", alt: "Dubai Marina in the foreground with Palm Jumeirah beyond", published: true, createdAt: now },
  { title: "The skyline at rest", category: "Skyline", image: "/images/hero-dubai-skyline.jpg", alt: "The Dubai skyline reflected in still water at night", published: true, createdAt: now },
  { title: "Palm Jumeirah at blue hour", category: "Waterfront", image: "/images/hero-dubai-villa.jpg", alt: "Waterfront villa at blue hour", published: true, createdAt: now },
  { title: "A quieter kind of luxury", category: "Interiors", image: "/images/interior-detail.jpg", alt: "Warm stone and brass interior details", published: true, createdAt: now },
  { title: "The city by water", category: "Communities", image: "/images/penthouse-marina.jpg", alt: "Dubai Marina skyline", published: true, createdAt: now },
  { title: "Room to settle", category: "Villas", image: "/images/hills-villa.jpg", alt: "Contemporary Dubai Hills villa", published: true, createdAt: now },
  { title: "A city made vertical", category: "Architecture", image: "/images/creek-waterfront.jpg", alt: "Dubai skyline over the creek", published: true, createdAt: now },
];

const testimonials = [
  { name: "A. & S. Morgan", designation: "Private buyers · London to Dubai", review: "KNC made a complex purchase feel remarkably calm. We felt advised at every turn, never pushed.", rating: 5, published: true, createdAt: now, updatedAt: now },
  { name: "Noura Al Mansoori", designation: "Seller · Palm Jumeirah", review: "They understood the story of our home before they spoke about the price. That changed the entire sale.", rating: 5, published: true, createdAt: now, updatedAt: now },
  { name: "Daniel R.", designation: "Investor · Singapore", review: "The shortlist was sharp, the numbers were honest, and the process had a rare sense of care.", rating: 5, published: true, createdAt: now, updatedAt: now },
  { name: "Maya K.", designation: "Buyer · Dubai Hills", review: "We found a home that felt right because KNC took the time to understand our everyday life.", rating: 5, published: true, createdAt: now, updatedAt: now },
  { name: "Omar H.", designation: "Landlord · Jumeirah", review: "Clear communication, excellent positioning, and a team that stayed close from listing to handover.", rating: 5, published: true, createdAt: now, updatedAt: now },
];

const developers: Omit<DeveloperDoc, "_id">[] = [
  {
    name: "Emaar Properties",
    slug: "emaar",
    shortDescription: "Dubai-based property developer known for major master-planned communities and residential developments.",
    description: "Emaar Properties is a publicly listed Dubai-based real estate developer established in 1997. The company is responsible for shaping landmark master communities across Dubai, including Downtown Dubai, Dubai Marina, Dubai Hills Estate, and Dubai Creek Harbour.",
    officialWebsite: "https://www.emaar.com",
    website: "https://www.emaar.com",
    featured: true,
    published: true,
    sortOrder: 1,
    areas: ["Downtown Dubai", "Dubai Marina", "Dubai Hills Estate", "Dubai Creek Harbour", "Arabian Ranches", "The Oasis", "Emaar South"],
    established: "1997",
    createdAt: now,
    updatedAt: now,
  },
  {
    name: "DAMAC Properties",
    slug: "damac",
    shortDescription: "Dubai-based property developer with residential, hospitality and branded-development projects.",
    description: "DAMAC Properties was founded in 2002 as a private residential, leisure, and commercial developer in Dubai. The developer is recognised for large-scale master communities including DAMAC Hills and luxury branded residential collaborations.",
    officialWebsite: "https://www.damacproperties.com",
    website: "https://www.damacproperties.com",
    featured: true,
    published: true,
    sortOrder: 2,
    areas: ["Dubai Marina", "Business Bay", "DAMAC Hills", "DAMAC Hills 2", "Dubai Maritime City", "Downtown Dubai"],
    established: "2002",
    createdAt: now,
    updatedAt: now,
  },
  {
    name: "Sobha Realty",
    slug: "sobha-realty",
    shortDescription: "Dubai-based developer known for residential communities and its vertically integrated development approach.",
    description: "Sobha Realty is an international luxury developer active in the UAE since 2003. Known for its backward-integrated construction and design model, its flagship Dubai developments include Sobha Hartland and Sobha Hartland II in Mohammed Bin Rashid City.",
    officialWebsite: "https://www.sobharealty.com",
    website: "https://www.sobharealty.com",
    featured: true,
    published: true,
    sortOrder: 3,
    areas: ["Mohammed Bin Rashid City", "Sobha Hartland", "Ras Al Khor", "Dubai Marina", "Sheikh Zayed Road"],
    established: "2003",
    createdAt: now,
    updatedAt: now,
  },
  {
    name: "Binghatti",
    slug: "binghatti",
    shortDescription: "Dubai-based developer with residential and branded developments across several Dubai communities.",
    description: "Binghatti Developers is a Dubai-headquartered property brand recognised for its distinct architectural styling and portfolio of branded residential partnerships across major central and residential districts.",
    officialWebsite: "https://www.binghatti.com",
    website: "https://www.binghatti.com",
    featured: true,
    published: true,
    sortOrder: 4,
    areas: ["Business Bay", "Downtown Dubai", "Jumeirah Village Circle", "Al Jaddaf", "Dubai Silicon Oasis"],
    established: "2008",
    createdAt: now,
    updatedAt: now,
  },
  {
    name: "Nakheel",
    slug: "nakheel",
    shortDescription: "Dubai-based master developer known for landmark waterfront destinations and master-planned residential communities.",
    description: "Nakheel is a major Dubai master developer celebrated for landmark coastal projects including Palm Jumeirah and Dubai Islands, alongside extensive family residential master communities throughout the emirate.",
    officialWebsite: "https://www.nakheel.com",
    website: "https://www.nakheel.com",
    featured: true,
    published: true,
    sortOrder: 5,
    areas: ["Palm Jumeirah", "Dubai Islands", "Jumeirah Islands", "Jumeirah Park", "Jumeirah Village Circle", "Al Furjan"],
    established: "2000",
    createdAt: now,
    updatedAt: now,
  },
  {
    name: "Danube Properties",
    slug: "danube",
    shortDescription: "Dubai-based property developer focusing on residential developments and private residences across Dubai.",
    description: "Danube Properties is the property development arm of the Danube Group, launched in 2014. The developer focuses on contemporary urban apartments with flexible payment models across established Dubai residential corridors.",
    officialWebsite: "https://www.danubeproperties.com",
    website: "https://www.danubeproperties.com",
    featured: false,
    published: true,
    sortOrder: 6,
    areas: ["Al Furjan", "Jumeirah Lake Towers", "Business Bay", "Arjan", "Dubai Silicon Oasis"],
    established: "2014",
    createdAt: now,
    updatedAt: now,
  },
  {
    name: "Ellington Properties",
    slug: "ellington",
    shortDescription: "Dubai-based boutique design-led property developer creating residential properties and communities.",
    description: "Ellington Properties, established in 2014, is a design-focused Dubai boutique developer producing high-specification residences across prime and emerging neighbourhoods.",
    officialWebsite: "https://www.ellingtonproperties.ae",
    website: "https://www.ellingtonproperties.ae",
    featured: false,
    published: true,
    sortOrder: 7,
    areas: ["Downtown Dubai", "Palm Jumeirah", "Mohammed Bin Rashid City", "Jumeirah Village Circle", "Business Bay"],
    established: "2014",
    createdAt: now,
    updatedAt: now,
  },
  {
    name: "Meraas",
    slug: "meraas",
    shortDescription: "Dubai-based developer known for destination-led residential, mixed-use, and waterfront communities.",
    description: "Meraas is a Dubai-based master development company with a portfolio of urban and coastal residential destinations including City Walk, Bluewaters Island, and Port de La Mer.",
    officialWebsite: "https://www.meraas.com",
    website: "https://www.meraas.com",
    featured: false,
    published: true,
    sortOrder: 8,
    areas: ["City Walk", "Bluewaters Island", "Port de La Mer", "Jumeirah", "Pearl Jumeira"],
    established: "2007",
    createdAt: now,
    updatedAt: now,
  },
];


const communities: Omit<CommunityDoc, "_id">[] = [
  {
    slug: "downtown-dubai",
    name: "Downtown Dubai",
    shortDescription: "The city at its centre",
    description:
      "Downtown sits around the Burj Khalifa, the Dubai Mall and the fountain lake, and is one of the emirate's designated freehold districts. Stock is almost entirely apartments in serviced towers, with a small number of penthouses on the upper floors. Buyers come for the address and the walkability; tenants for the metro, the offices on Sheikh Zayed Road and the shortest commute in the city.",
    location: "Central Dubai",
    image: "/images/hero-dubai-skyline.jpg",
    highlights: ["Freehold", "Burj Khalifa and fountain views", "Metro and Sheikh Zayed Road access", "Serviced towers"],
    propertyTypes: ["Apartment", "Penthouse", "Retail"],
    featured: true,
    published: true,
    sortOrder: 1,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "dubai-marina",
    name: "Dubai Marina",
    shortDescription: "The city by water",
    description:
      "A man-made canal district of high-rise towers around a working marina, with the Marina Walk running its full length. One of Dubai's oldest freehold areas and still among the most liquid for resale and for letting, with a rental market that turns over quickly. Apartments dominate; penthouses sit at the top of the older towers.",
    location: "Dubai Marina",
    image: "/images/dubai-marina-promenade.jpg",
    highlights: ["Freehold", "Marina Walk and JBR beach", "Tram and metro links", "Strong rental demand"],
    propertyTypes: ["Apartment", "Penthouse"],
    featured: true,
    published: true,
    sortOrder: 2,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "palm-jumeirah",
    name: "Palm Jumeirah",
    shortDescription: "Island life, redefined",
    description:
      "The fronds hold signature villas with private beach access; the trunk and the crescent hold apartments and hotel residences. Supply is fixed, which is what keeps values on the island distinct from the mainland. Villas are bought for the beach frontage rather than the floor area.",
    location: "Palm Jumeirah",
    image: "/images/palm-jumeirah-aerial.jpg",
    highlights: ["Freehold", "Private beach frontage", "Fixed supply", "Villas and branded residences"],
    propertyTypes: ["Villa", "Apartment", "Penthouse"],
    featured: true,
    published: true,
    sortOrder: 3,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "business-bay",
    name: "Business Bay",
    shortDescription: "A vertical pulse",
    description:
      "A mixed-use district on the Dubai Water Canal, immediately south of Downtown. Towers combine offices, serviced apartments and residential floors, which is why entry prices sit below Downtown for a comparable commute. Studios and one-bedrooms let quickly here.",
    location: "Business Bay",
    image: "/images/business-bay-night.jpg",
    highlights: ["Freehold", "Dubai Water Canal", "Mixed residential and office", "Entry-level studios"],
    propertyTypes: ["Apartment", "Duplex", "Office"],
    featured: false,
    published: true,
    sortOrder: 4,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "jumeirah",
    name: "Jumeirah",
    shortDescription: "An established ease",
    description:
      "An older coastal strip of low-rise villas and townhouses between Jumeirah Beach Road and the sea. Plots are generous and the streets are quiet; parts of the area are freehold and parts remain leasehold, so ownership needs checking plot by plot.",
    location: "Jumeirah 1-3",
    image: "/images/jumeirah-coast-burj-al-arab.jpg",
    highlights: ["Beach access", "Low-rise villas", "Established schools", "Mixed freehold and leasehold"],
    propertyTypes: ["Villa", "Townhouse"],
    featured: false,
    published: true,
    sortOrder: 5,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "arabian-ranches",
    name: "Arabian Ranches",
    shortDescription: "Space to settle",
    description:
      "An Emaar-built villa community off Sheikh Mohammed Bin Zayed Road, arranged in named sub-communities around a golf course and a central retail centre. Almost entirely family villas and townhouses, taken on long leases or bought outright; there are no apartment towers.",
    location: "Arabian Ranches",
    image: "/images/community-garden-villas.jpg",
    highlights: ["Freehold", "Golf course", "Family villas and townhouses", "Schools on the community"],
    propertyTypes: ["Villa", "Townhouse"],
    featured: false,
    published: true,
    sortOrder: 6,
    createdAt: now,
    updatedAt: now,
  },
];

const insights: Omit<MarketInsightDoc, "_id">[] = [
  {
    slug: "freehold-ownership-in-dubai",
    title: "Freehold ownership: what a foreign buyer actually owns",
    category: "Ownership",
    summary:
      "Since 2002 Dubai has allowed foreign nationals to own property outright, but only inside designated freehold areas. Everything else is leasehold or usufruct.",
    content:
      "Regulation No. 3 of 2006 sets out the areas in Dubai where a non-GCC national may hold freehold title. Downtown Dubai, Dubai Marina, Palm Jumeirah, Business Bay, Dubai Hills Estate, Jumeirah Village Circle, Arabian Ranches and Dubai Creek Harbour all sit inside that list; older parts of the city do not.\n\nInside a freehold area the buyer owns the unit and a share of the common property outright, registered in their own name at the Dubai Land Department, with no time limit and no requirement to be resident. Outside those areas, a foreign buyer can normally take a leasehold or usufruct interest of up to 99 years instead, which is a right to use rather than ownership.\n\nThe practical step is to confirm the designation before an offer, not after. Title is registered plot by plot, and a single neighbourhood can contain both.",
    source: "Dubai Land Department",
    sourceUrl: "https://dubailand.gov.ae/",
    image: "/images/hero-dubai-skyline.jpg",
    published: true,
    featured: true,
    sortOrder: 1,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "what-it-costs-to-buy-in-dubai",
    title: "What it costs to buy, beyond the price",
    category: "Buying",
    summary:
      "The transfer fee is the largest single cost on top of the price. Budget for it, the agency fee and the registration fees before agreeing a number.",
    content:
      "The Dubai Land Department charges a transfer fee of 4% of the purchase price, conventionally split between buyer and seller but in practice almost always paid by the buyer. On top of that sit a title deed issuance fee and a registration trustee fee, which are fixed amounts rather than percentages and scale with the price band.\n\nAgency commission is typically 2% of the purchase price plus VAT. A mortgage adds a registration fee of 0.25% of the loan amount, plus the lender's own arrangement and valuation fees.\n\nAs a rule of thumb, allow 6-7% of the purchase price in costs for a cash purchase and a little more with finance. Service charges are then an annual cost, set per square foot and collected through the Mollak system, and they vary widely between a serviced tower and a villa community.",
    source: "Dubai Land Department",
    sourceUrl: "https://dubailand.gov.ae/",
    image: "/images/downtown-safa-park.jpg",
    published: true,
    featured: true,
    sortOrder: 2,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "how-off-plan-payments-are-protected",
    title: "How off-plan payments are protected",
    category: "Off-plan",
    summary:
      "Every dirham paid on an off-plan sale must go into a project escrow account, not to the developer directly. That protection is the point of the law.",
    content:
      "Law No. 8 of 2007 requires a developer selling off-plan in Dubai to open an escrow account for each project with an accredited bank. Buyer payments go into that account and are released to the developer against construction milestones certified by an independent engineer, so money paid cannot be moved to another project.\n\nThe sale itself is recorded on the Oqood system, which registers the buyer's interest before a title deed exists. A buyer should be able to see the project's registration number, its escrow account and its completion percentage before paying a reservation.\n\nPayment plans are set by the developer and vary: a common structure is 20% on booking, staged payments to handover and a balance on completion, with some plans running on for years after handover.",
    source: "Dubai Land Department",
    sourceUrl: "https://dubailand.gov.ae/",
    image: "/images/maritime-city-towers.jpg",
    published: true,
    featured: false,
    sortOrder: 3,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "property-and-the-golden-visa",
    title: "Property and the ten-year Golden Visa",
    category: "Residency",
    summary:
      "A property investment of AED 2 million or more can support a ten-year renewable residence visa for the owner and their family.",
    content:
      "Under the UAE's long-term residence scheme, an investor who owns property in the UAE worth at least AED 2 million may apply for a ten-year renewable Golden Visa. The threshold applies to the value recorded on the title deed, and it can be met by one property or by more than one held together.\n\nOff-plan property can qualify where the units are bought from an approved developer, and mortgaged property can qualify subject to the lender's and the authority's conditions. The visa extends to a spouse and children, and holders may sponsor domestic staff.\n\nA smaller investment threshold supports a two-year investor visa. Both are applications to the immigration authority rather than something that comes automatically with a purchase, and the property must be retained for the visa to remain valid.",
    source: "UAE Government Portal",
    sourceUrl: "https://u.ae/",
    image: "/images/burj-khalifa-aerial.jpg",
    published: true,
    featured: false,
    sortOrder: 4,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "renting-in-dubai-what-governs-it",
    title: "Renting in Dubai: what governs the tenancy",
    category: "Renting",
    summary:
      "Rents are quoted annually, contracts are registered through Ejari, and increases at renewal are capped by the RERA rental index.",
    content:
      "A Dubai tenancy is quoted as an annual rent and paid in a number of cheques, commonly one to four; fewer cheques usually buys a lower headline rent. The contract must be registered through Ejari, which is what gives the tenancy legal standing and is required for utilities and for many visa processes.\n\nAt renewal, a landlord may only increase the rent within the bands set by the RERA rental index, which compares the current rent against the average for similar units in the same area. Where the rent is already at or near the index, no increase is permitted. Notice of any increase must be given 90 days before renewal.\n\nA landlord seeking vacant possession must give 12 months' notice through a notary or registered post, and only on the grounds set out in the law.",
    source: "Dubai Land Department / RERA",
    sourceUrl: "https://dubailand.gov.ae/",
    image: "/images/dubai-marina-dusk.jpg",
    published: true,
    featured: false,
    sortOrder: 5,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "service-charges-and-what-they-cover",
    title: "Service charges, and what they actually cover",
    category: "Ownership",
    summary:
      "Service charges are set per square foot, approved by RERA and collected through Mollak. They are the running cost that most often surprises a first-time owner.",
    content:
      "Every owner in a jointly owned property pays an annual service charge towards the upkeep of the common areas: the lifts, the chiller plant, the pool, the landscaping, security, insurance and a reserve fund for major works. The charge is expressed in dirhams per square foot of the unit and billed quarterly.\n\nThe budget behind it has to be approved by RERA and is collected through Mollak, the escrow system for owners' association funds, so the money sits outside the management company's own accounts. Approved rates for a building are published and can be checked before purchase.\n\nRates vary widely. A villa community with little shared infrastructure sits at the low end; a serviced tower with extensive amenities and district cooling sits well above it. On a yield calculation the service charge is the difference between a gross and a net return, so it belongs in the arithmetic from the start.",
    source: "Dubai Land Department / Mollak",
    sourceUrl: "https://dubailand.gov.ae/",
    image: "/images/marina-resort-greens.jpg",
    published: true,
    featured: false,
    sortOrder: 6,
    createdAt: now,
    updatedAt: now,
  },
];

/*
 * Upsert on whatever natural key a record carries. Gallery items have a title rather than a
 * slug, and the old code fell back to "insert only when the collection is empty" for those,
 * so new gallery entries were silently skipped once the first five existed.
 */
async function seedCollection(collection: Collection<any>, documents: any[]) {
  if (!documents.length) return;
  const key = typeof documents[0].slug === "string" ? "slug"
    : typeof documents[0].title === "string" ? "title"
    : null;
  if (key) {
    await collection.bulkWrite(documents.map((document) => ({
      updateOne: { filter: { [key]: document[key] }, update: { $set: document }, upsert: true },
    })));
    return;
  }
  if ((await collection.countDocuments()) === 0) await collection.insertMany(documents);
}

export async function seedDatabase() {
  const db = getDb();
  // Migrate the original Azure House slug so existing databases keep working
  // while the public URL remains consistent with the frontend route.
  await db.collection<PropertyDoc>("properties").updateOne(
    { slug: "azure-house-palm-jumeirah" },
    { $set: { slug: "palm-jumeirah-azure", updatedAt: new Date() } },
  );
  await seedCollection(db.collection<DeveloperDoc>("developers"), developers);
  await seedCollection(db.collection<PropertyDoc>("properties"), properties);
  await seedCollection(db.collection<ProjectDoc>("projects"), projects);
  await seedCollection(db.collection<BlogPostDoc>("posts"), posts);
  await seedCollection(db.collection<GalleryItemDoc>("gallery"), gallery);
  await seedCollection(db.collection("testimonials"), testimonials);
  await seedCollection(db.collection<CommunityDoc>("communities"), communities);
  await seedCollection(db.collection<MarketInsightDoc>("insights"), insights);

  const email = process.env.ADMIN_EMAIL;
  const password = process.env.ADMIN_PASSWORD;
  if (email?.trim() && password && !password.startsWith("replace-with-")) {
    const users = db.collection<UserDoc>("users");
    const normalizedEmail = email.trim().toLowerCase();
    const passwordHash = await bcrypt.hash(password, 12);
    await users.updateOne(
      { email: normalizedEmail },
      { $set: { email: normalizedEmail, passwordHash, role: "admin" }, $setOnInsert: { createdAt: new Date() } },
      { upsert: true },
    );
  }
}