/**
 * ⚠️ SAMPLE / DEMO DATA ⚠️
 * Everything in this file (properties, blog posts, gallery items) is
 * placeholder content used to preview the site's layout. None of it is
 * real. Before the site goes live for a real client, either:
 *   1) Replace the entries below with your actual listings and posts, or
 *   2) Leave this file alone and use the /admin panel (Login page) to
 *      add, edit, and delete real properties/blog posts once the site
 *      is deployed — the admin panel writes to the same database.
 */
import bcrypt from "bcryptjs";
import type { Collection } from "mongodb";
import { getDb } from "./mongodb";
import type { BlogPostDoc, GalleryItemDoc, ProjectDoc, PropertyDoc, UserDoc } from "./models";

const now = new Date();

const properties: Omit<PropertyDoc, "_id">[] = [
  {
    slug: "palm-jumeirah-azure",
    title: "Azure House",
    location: "Frond M, Palm Jumeirah",
    community: "Palm Jumeirah",
    type: "Villa",
    status: "For sale",
    price: 24500000,
    currency: "AED",
    bedrooms: 5,
    bathrooms: 7,
    size: 8420,
    description: "A private waterfront villa shaped around quiet mornings, generous entertaining, and direct access to the water.",
    images: ["/images/hero-dubai-villa.jpg", "/images/interior-detail.jpg"],
    amenities: ["Private beach", "Infinity pool", "Staff suite", "Sea views"],
    featured: true,
    published: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "meridian-residence-dubai-marina",
    title: "The Meridian Residence",
    location: "Dubai Marina",
    community: "Dubai Marina",
    type: "Penthouse",
    status: "For sale",
    price: 8900000,
    currency: "AED",
    bedrooms: 3,
    bathrooms: 4,
    size: 2980,
    description: "A turnkey skyline residence with a wide marina outlook and a considered, light-filled interior.",
    images: ["/images/penthouse-marina.jpg", "/images/interior-detail.jpg"],
    amenities: ["Sea view", "Concierge", "Residents lounge", "Private lift"],
    featured: true,
    published: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "courtyard-17-dubai-hills",
    title: "Courtyard 17",
    location: "Dubai Hills Estate",
    community: "Dubai Hills Estate",
    type: "Villa",
    status: "For sale",
    price: 11750000,
    currency: "AED",
    bedrooms: 4,
    bathrooms: 5,
    size: 4870,
    description: "A calm contemporary family home on a quiet street, with garden rooms that bring the outside in.",
    images: ["/images/hills-villa.jpg", "/images/interior-detail.jpg"],
    amenities: ["Private garden", "Study", "Garage", "Community pool"],
    featured: false,
    published: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "address-sky-view-downtown",
    title: "The Address Sky View",
    location: "Downtown Dubai",
    community: "Downtown Dubai",
    type: "Apartment",
    status: "For sale",
    price: 4250000,
    currency: "AED",
    bedrooms: 2,
    bathrooms: 3,
    size: 1640,
    description: "A polished city apartment with Burj Khalifa views and the service of one of Downtown’s most recognisable addresses.",
    images: ["/images/creek-waterfront.jpg", "/images/interior-detail.jpg"],
    amenities: ["Burj view", "Valet parking", "Pool", "Fitness studio"],
    featured: false,
    published: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "garden-residence-jumeirah",
    title: "Garden Residence",
    location: "Jumeirah 2",
    community: "Jumeirah",
    type: "Villa",
    listingType: "sale",
    status: "For sale",
    price: 13800000,
    currency: "AED",
    bedrooms: 4,
    bathrooms: 5,
    size: 5200,
    description: "A leafy Jumeirah residence with generous proportions, considered landscaping, and a private pool.",
    images: ["/images/hills-villa.jpg", "/images/interior-detail.jpg"],
    amenities: ["Private pool", "Garden", "Maid's room", "Covered parking"],
    highlights: ["Quiet residential street", "Minutes from the beach"],
    featured: false,
    published: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "creekside-loft",
    title: "Creekside Loft",
    location: "Dubai Creek Harbour",
    community: "Dubai Creek Harbour",
    type: "Apartment",
    listingType: "sale",
    status: "For sale",
    price: 2850000,
    currency: "AED",
    bedrooms: 2,
    bathrooms: 2,
    size: 1350,
    description: "A bright, high-floor apartment with a wide water outlook and an easy connection to the new Creek neighbourhood.",
    images: ["/images/creek-waterfront.jpg", "/images/interior-detail.jpg"],
    amenities: ["Water view", "Pool", "Gym", "Concierge"],
    highlights: ["High floor", "Walkable waterfront"],
    featured: false,
    published: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "marina-sunline",
    title: "Marina Sunline",
    location: "Dubai Marina",
    community: "Dubai Marina",
    type: "Apartment",
    listingType: "rent",
    status: "For rent",
    price: 220000,
    currency: "AED",
    bedrooms: 1,
    bathrooms: 2,
    size: 980,
    description: "A fully furnished marina apartment with sunset-facing views, hotel-style amenities, and a polished finish.",
    images: ["/images/penthouse-marina.jpg", "/images/interior-detail.jpg"],
    amenities: ["Furnished", "Pool", "Gym", "Parking"],
    highlights: ["Available now", "Sunset view"],
    featured: false,
    published: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "desert-modern-al-barari",
    title: "Desert Modern",
    location: "Al Barari",
    community: "Al Barari",
    type: "Villa",
    listingType: "sale",
    status: "For sale",
    price: 17900000,
    currency: "AED",
    bedrooms: 5,
    bathrooms: 6,
    size: 6900,
    description: "A sculptural family home surrounded by greenery, with a private courtyard and a calm indoor-outdoor rhythm.",
    images: ["/images/hills-villa.jpg", "/images/hero-dubai-villa.jpg"],
    amenities: ["Courtyard", "Private pool", "Cinema", "Smart home"],
    highlights: ["Landscaped setting", "Architect-designed"],
    featured: false,
    published: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "city-light-downtown",
    title: "City Light Residence",
    location: "Downtown Dubai",
    community: "Downtown Dubai",
    type: "Apartment",
    listingType: "sale",
    status: "For sale",
    price: 3650000,
    currency: "AED",
    bedrooms: 2,
    bathrooms: 2,
    size: 1480,
    description: "A refined city base with clean lines, skyline views, and direct access to Downtown's cultural and retail life.",
    images: ["/images/creek-waterfront.jpg", "/images/penthouse-marina.jpg"],
    amenities: ["Skyline view", "Pool", "Valet parking", "Residents lounge"],
    highlights: ["Turnkey condition", "Central address"],
    featured: false,
    published: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "canal-house-business-bay",
    title: "Canal House",
    location: "Business Bay",
    community: "Business Bay",
    type: "Apartment",
    listingType: "sale",
    status: "For sale",
    price: 3150000,
    currency: "AED",
    bedrooms: 2,
    bathrooms: 3,
    size: 1420,
    description: "A composed canal-side residence with generous daylight, clean architectural lines, and a connected central address.",
    images: ["/images/creek-waterfront.jpg", "/images/interior-detail.jpg"],
    amenities: ["Canal view", "Pool", "Gym", "Concierge"],
    highlights: ["Central location", "Move-in ready"],
    featured: false,
    published: true,
    createdAt: now,
    updatedAt: now,
  },
];

const projects: Omit<ProjectDoc, "_id">[] = [
  {
    slug: "the-oasis-by-emaar",
    title: "The Oasis",
    developer: "Emaar",
    location: "Dubailand",
    startingPrice: 5500000,
    handover: "Q4 2028",
    description: "A low-density collection of villas and gardens designed around water, landscape, and long-term liveability.",
    image: "/images/hills-villa.jpg",
    featured: true,
    published: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "bay-by-cavalli",
    title: "Bay by Cavalli",
    developer: "DAMAC",
    location: "Dubai Maritime City",
    startingPrice: 3200000,
    handover: "Q2 2028",
    description: "A waterfront address for buyers looking for a distinctive design language, resort amenities, and a central coastal position.",
    image: "/images/penthouse-marina.jpg",
    featured: true,
    published: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "the-valley-by-emaar",
    title: "The Valley",
    developer: "Emaar",
    location: "Jebel Ali",
    category: "Villas",
    status: "Launching",
    startingPrice: 2900000,
    handover: "Q1 2029",
    completionDate: "Q1 2029",
    description: "A new collection of family villas set around open landscapes, trails, and everyday community life.",
    image: "/images/hills-villa.jpg",
    gallery: ["/images/hills-villa.jpg", "/images/creek-waterfront.jpg"],
    amenities: ["Community pool", "Sports fields", "Trails", "Town centre"],
    highlights: ["Family-oriented community", "Flexible payment plan"],
    featured: false,
    published: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "sobha-one",
    title: "Sobha One",
    developer: "Sobha Realty",
    location: "Ras Al Khor",
    category: "Apartments",
    status: "Under construction",
    startingPrice: 2100000,
    handover: "Q4 2028",
    description: "A golf-side vertical neighbourhood with generous views, thoughtful amenities, and a strong central position.",
    image: "/images/penthouse-marina.jpg",
    featured: false,
    published: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "avenue-al-jaddaf",
    title: "Avenue",
    developer: "Azizi",
    location: "Al Jaddaf",
    category: "Waterfront",
    status: "Launching",
    startingPrice: 1250000,
    handover: "Q3 2027",
    description: "A compact waterfront address for buyers seeking access, amenity, and a considered entry into the Dubai market.",
    image: "/images/creek-waterfront.jpg",
    featured: false,
    published: true,
    createdAt: now,
    updatedAt: now,
  },
];

const posts: Omit<BlogPostDoc, "_id">[] = [
  {
    slug: "where-to-live-in-dubai",
    title: "Where to live in Dubai when the city needs to feel like home",
    excerpt: "A local read on choosing between the energy of Downtown, the water of the Marina, and the space of the suburbs.",
    content: "Dubai rewards a slower first question: how do you want an ordinary Tuesday to feel? From walkable city life to private garden streets, the right community is the one that supports the life you are building.",
    category: "Area guide",
    image: "/images/creek-waterfront.jpg",
    author: "KNC Horizon",
    published: true,
    publishedAt: now,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "buying-off-plan-in-dubai",
    title: "A clear-eyed guide to buying off-plan in Dubai",
    excerpt: "The questions worth asking about a developer, a handover, a payment plan, and the value of a future address.",
    content: "Off-plan property can offer access to a new generation of communities, but the strongest decisions come from context. Understand the developer, the delivery timeline, the surrounding infrastructure, and how the payment plan fits your horizon.",
    category: "Investment",
    image: "/images/interior-detail.jpg",
    author: "KNC Horizon",
    published: true,
    publishedAt: now,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "the-dubai-rental-reset",
    title: "The Dubai rental reset: what tenants should look for now",
    excerpt: "A practical checklist for comparing a home beyond the headline rent.",
    content: "The strongest rental decisions come from looking at the whole year, not only the first month. Consider the building, the commute, the renewal terms, the maintenance response, and the daily ease of the address.",
    category: "Renting",
    image: "/images/penthouse-marina.jpg",
    author: "KNC Horizon",
    published: true,
    publishedAt: now,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "designing-a-better-home-search",
    title: "Designing a better home search",
    excerpt: "The right shortlist is not the longest one. It is the one that makes the decision clearer.",
    content: "A good search begins with a few strong filters and the confidence to remove what does not fit. When the brief reflects how you actually live, the right homes become easier to recognise.",
    category: "Perspective",
    image: "/images/hero-dubai-villa.jpg",
    author: "KNC Horizon",
    published: true,
    publishedAt: now,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "a-first-time-buyers-map",
    title: "A first-time buyer's map of Dubai",
    excerpt: "The questions that help a first purchase feel like a confident beginning.",
    content: "Start with the life you want to support, then work backwards through location, building quality, budget, and timeline. A property is a financial decision, but it is also a daily one.",
    category: "Buying",
    image: "/images/hills-villa.jpg",
    author: "KNC Horizon",
    published: true,
    publishedAt: now,
    createdAt: now,
    updatedAt: now,
  },
];

const gallery: Omit<GalleryItemDoc, "_id">[] = [
  { title: "Palm Jumeirah at blue hour", category: "Waterfront", image: "/images/hero-dubai-villa.jpg", alt: "Waterfront villa at blue hour", createdAt: now },
  { title: "A quieter kind of luxury", category: "Interiors", image: "/images/interior-detail.jpg", alt: "Warm stone and brass interior details", createdAt: now },
  { title: "The city by water", category: "Communities", image: "/images/penthouse-marina.jpg", alt: "Dubai Marina skyline", createdAt: now },
  { title: "Room to settle", category: "Villas", image: "/images/hills-villa.jpg", alt: "Contemporary Dubai Hills villa", createdAt: now },
  { title: "A city made vertical", category: "Architecture", image: "/images/creek-waterfront.jpg", alt: "Dubai skyline over the creek", createdAt: now },
];

const testimonials = [
  { name: "A. & S. Morgan", designation: "Private buyers · London to Dubai", review: "KNC made a complex purchase feel remarkably calm. We felt advised at every turn, never pushed.", rating: 5, published: true, createdAt: now, updatedAt: now },
  { name: "Noura Al Mansoori", designation: "Seller · Palm Jumeirah", review: "They understood the story of our home before they spoke about the price. That changed the entire sale.", rating: 5, published: true, createdAt: now, updatedAt: now },
  { name: "Daniel R.", designation: "Investor · Singapore", review: "The shortlist was sharp, the numbers were honest, and the process had a rare sense of care.", rating: 5, published: true, createdAt: now, updatedAt: now },
  { name: "Maya K.", designation: "Buyer · Dubai Hills", review: "We found a home that felt right because KNC took the time to understand our everyday life.", rating: 5, published: true, createdAt: now, updatedAt: now },
  { name: "Omar H.", designation: "Landlord · Jumeirah", review: "Clear communication, excellent positioning, and a team that stayed close from listing to handover.", rating: 5, published: true, createdAt: now, updatedAt: now },
];

async function seedCollection(collection: Collection<any>, documents: any[]) {
  if (!documents.length) return;
  if (typeof documents[0].slug === "string") {
    await collection.bulkWrite(documents.map((document) => ({
      updateOne: { filter: { slug: document.slug }, update: { $setOnInsert: document }, upsert: true },
    })));
    return;
  }
  if ((await collection.countDocuments()) === 0) await collection.insertMany(documents);
}

export async function seedDatabase() {
  const db = getDb();
  // Migrate the original Azure House slug so existing databases keep working
  // while the public URL remains consistent with the frontend route.
  await db.collection<PropertyDoc>("properties").updateOne(
    { slug: "azure-house-palm-jumeirah" },
    { $set: { slug: "palm-jumeirah-azure", updatedAt: new Date() } },
  );
  await seedCollection(db.collection<PropertyDoc>("properties"), properties);
  await seedCollection(db.collection<ProjectDoc>("projects"), projects);
  await seedCollection(db.collection<BlogPostDoc>("posts"), posts);
  await seedCollection(db.collection<GalleryItemDoc>("gallery"), gallery);
  await seedCollection(db.collection("testimonials"), testimonials);

  const email = process.env.ADMIN_EMAIL;
  const password = process.env.ADMIN_PASSWORD;
  if (email?.trim() && password && !password.startsWith("replace-with-")) {
    const users = db.collection<UserDoc>("users");
    const normalizedEmail = email.trim().toLowerCase();
    const passwordHash = await bcrypt.hash(password, 12);
    await users.updateOne(
      { email: normalizedEmail },
      { $set: { email: normalizedEmail, passwordHash, role: "admin" }, $setOnInsert: { createdAt: new Date() } },
      { upsert: true },
    );
  }
}